# Generated by Django 3.2 on 2023-04-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_unique_author'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_author',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_author_title'),
        ),
    ]
